version: '3.8'
services:
  backend:
    build: ./src/backend
    ports:
      - '3001:3001'
    depends_on:
      - db
  frontend:
    build: ./src/frontend
    ports:
      - '3000:3000'
    depends_on:
      - backend
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '5432:5432'
