@startuml Activity-Template
title Processo [Nome Processo] - Diagramma di Attività

|#LightBlue|Attore 1|
start
:Azione 1;
:Azione 2;

|#LightGreen|Attore 2|
:Azione 3;

if (Condizione?) then (sì)
  :Azione 4;
else (no)
  :Azione 5;
  stop
endif

|#LightBlue|Attore 1|
:Azione 6;
stop

@enduml
