@startuml ER-Diagram-Template
title Modello [Nome Dominio]

entity EntitaA {
  +id: long <<PK>>
  --
  +attributo1: String
  +attributo2: int
}

entity EntitaB {
  +id: long <<PK>>
  --
  +attributo3: String
  +id_entita_a: long <<FK>>
}

EntitaA "1" -- "0..*" EntitaB

@enduml
