@startuml UseCase-Template
title Sistema [Nome Sistema] - Casi d'Uso

left to right direction

actor "Attore Principale" as MainActor
actor "Altro Attore" as OtherActor

rectangle "Nome del Sistema" {
  usecase "Funzionalità A" as UCA
  usecase "Funzionalità B" as UCB
  usecase "Funzionalità C" as UCC
}

MainActor --> UCA
MainActor --> UCB
OtherActor --> UCC

@enduml
